GET http://localhost:8000/api/test HTTP/1.1

###

POST  http://localhost:8000/api/signup HTTP/1.1
Content-Type: 'application/json'

{
    "username": "sabayblc",
    "fullname": "Sabyblc",
    "email": "sabayblc@gmail.com",
    "password": "sabayblc"
}

###

GET http://localhost:8000/api/users HTTP/1.1

### get verify code
POST http://localhost:8000/api/get_verify_code HTTP/1.1
Content-Type: 'application/json'

{
    "email": "sabayblc@gmail.com"
}

### check verify code

POST http://localhost:8000/api/check_verify_code HTTP/1.1
Content-Type: 'application/json'

{
    "email": "sabayblc@gmail.com",
    "confirmation_code": "161485151916040adbf5b995"
}

### login account and store token
POST http://localhost:8000/api/login HTTP/1.1
Content-Type: 'application/json'

{
    "email": "sabayblc@gmail.com",
    "password": "sabayblc"
}

### change_info_after signup
POST http://localhost:8000/api/signup_info_after_signup HTTP/1.1
Content-Type: 'application/json'
Authorization: Bearer 2|nx7eiLP26cPAxwST28RtT3pSbCTSDmjEmVVODvr5

{
    "image": "/home/linux/Pictures/bai4.png"
}

### test auth with token
POST http://localhost:8000/api/token HTTP/1.1
Content-Type: 'application/json'
Authorization: Bearer 2|nx7eiLP26cPAxwST28RtT3pSbCTSDmjEmVVODvr5

{
    "email": "samreach@gmail.com"
}
